### ISSUE TITLE
Doesn't fuzzy search file contents with -e option

### ISSUE THREAD

**Issue by robdmc** [Magnushhoie/fuz#1]
Hello.

Great tool!  I've always wanted something like this.  Thanks for writing.

I am on mac-os installed with brew.

When I run with the -e option, it looks like the fuzzy search is looking for file names instead of the contents of the file.  Is this expected behavior?

**Comment by Magnushhoie** [comment]
Hi Rob, thanks for the kind words and glad you're finding it useful :)

The -e flag also showing file-names is intended as a convenience feature. The most common usage patterns (in my experience) are 1) Search for specific text using 'fuz' or 2) Add some text to a specific file using 'fuz -e'. 

The latter is easier to perform if it defaults to the file list overview, and faster to type if its just 'fuz -e' instead of 'fuz -e -n'.

However, this makes it a bit more difficult to open a file at a specific matched line in vim. I've modified the echo message shown after selecting a match to include also the matched line in a format that can be copy pasted to open in vim.

```
# Copy this echoed message (shown after selecting a match)
"notes.txt" +622

# Paste after 'vim' to open at specific line 622
vim "notes.txt" +622
```

**Comment by robdmc** [comment]
just got back to this.  Still been using this tool regularly and loving it.  Thanks for the updates.  That will help.

**Comment by Magnushhoie** [comment]
Have added a fuz --vimsearch option for this in the dev branch. Also sorting results by time and preserving line order, at the cost of single threading. Will merge in a few days to allow for testing.
